program    = (function | expr)*;
function   = "function" ident "(" (ident ("," ident)*)? ")" seq;
expr       = call | assignment | if | while | seq | relational;
if         = "if" "(" expr ")" expr "else" expr;
while      = "while" "(" expr ")" expr;
seq        = "{" expr+ "}";
call       = ident "(" (expr ("," expr)*)? ")";
assignment = ident "=" expr;
relational = add ("<" add | "<=" add | ">" add | ">=" add)*;
add        = mul ("+" mul | "-" mul)*;
mul        = unary ("*" unary | "/" unary)*;
unary      = ("+" | "-")? primary;
primary    = NUMBER | ident | "(" expr ")";
